--
-- PostgreSQL database dump
--

\restrict VAcpTeu0Xfajg5491wqWCtglPiSqrqOLgdSdUIeBYZbFdm0kb4NspPeqTioea7B

-- Dumped from database version 15.8
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: quiz_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.quiz_status AS ENUM (
    'All',
    'Done',
    'Pending',
    'Locked'
);


--
-- Name: user_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.user_type AS ENUM (
    'admin',
    'student',
    'teacher'
);


--
-- Name: TYPE user_type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TYPE public.user_type IS 'user type for hope hub';


--
-- Name: register_user(uuid, text, text, text, jsonb, text); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.register_user(p_user_id uuid, p_full_name text, p_email text, p_user_type text, p_lecture_progress jsonb, p_class_code text DEFAULT NULL::text) RETURNS void
    LANGUAGE plpgsql
    AS $$
begin
  insert into profile (uuid, full_name, email, user_type)
  values (
    p_user_id,
    p_full_name,
    p_email,
    p_user_type::user_type
  );

  insert into lecture_progress (uuid, lecture_progress)
  values (p_user_id, p_lecture_progress);

  insert into physical_fitness_test (uuid)
  values (p_user_id);

  -- Conditional insert based on user_type
  if p_user_type = 'student' then
    insert into student_class_code (uuid, class_code)
    values (p_user_id, p_class_code);
  elsif p_user_type = 'teacher' then
    insert into teacher_class_code (uuid, class_code)
    values (p_user_id, p_class_code);
  end if;

exception
  when others then
    raise exception 'Registration failed: %', SQLERRM;
end;
$$;


--
-- Name: retrieve_students_by_class(text); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.retrieve_students_by_class(class_code_input text) RETURNS TABLE(full_name text, email text, uuid uuid, lecture_progress jsonb, pre_physical_fitness_test json, post_physical_fitness_test json, quiz_data jsonb)
    LANGUAGE plpgsql
    AS $$
begin
  return query
  select
    p.full_name,
    p.email,
    p.uuid,
    (
      select jsonb_agg(lp.lecture_progress)
      from lecture_progress lp
      where lp.uuid = p.uuid
    ) as lecture_progress,
    (
      select json_agg(pft.pre_physical_fitness_test)
      from physical_fitness_test pft
      where pft.uuid = p.uuid
    ) as pre_physical_fitness_test,
    (
      select json_agg(pft.post_physical_fitness_test)
      from physical_fitness_test pft
      where pft.uuid = p.uuid
    ) as post_physical_fitness_test,
    (
      select jsonb_agg(
        jsonb_build_object(
          'quiz_number', qr.quiz_id,
          'score', qr.score,
          'status', qr.status,
          'total_items', qr.total_items
        )
      )
      from quiz_progress qr
      where qr.user_id = p.uuid
    ) as quiz_data
  from profile p
  inner join student_class_code scc on scc.uuid = p.uuid
  where scc.class_code = class_code_input;
end;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: student_class_code; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_class_code (
    id bigint NOT NULL,
    class_code text,
    uuid uuid
);


--
-- Name: TABLE student_class_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.student_class_code IS 'table for the class code of students';


--
-- Name: class_code_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.student_class_code ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.class_code_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lecture_progress; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lecture_progress (
    uuid uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    lecture_progress jsonb
);


--
-- Name: physical_fitness_test; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.physical_fitness_test (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    uuid uuid DEFAULT gen_random_uuid(),
    pre_physical_fitness_test jsonb,
    post_physical_fitness_test json
);


--
-- Name: physical_fitness_test_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.physical_fitness_test ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.physical_fitness_test_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile (
    uuid uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    full_name text,
    email text,
    user_type public.user_type
);


--
-- Name: quiz; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quiz (
    id bigint NOT NULL,
    title character varying NOT NULL,
    description text NOT NULL,
    questions json NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    quiz_number smallint,
    lecture_title character varying
);


--
-- Name: quiz_progress; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quiz_progress (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    quiz_id smallint NOT NULL,
    question_index smallint DEFAULT '0'::smallint,
    score smallint,
    points smallint,
    status public.quiz_status NOT NULL,
    questions_answered json,
    total_items smallint,
    date_taken date,
    start_time timestamp with time zone,
    end_time timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    questions_shuffled json,
    remaining_time smallint
);


--
-- Name: quiz_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quiz_progress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quiz_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quiz ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teacher_class_code; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teacher_class_code (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    uuid uuid DEFAULT gen_random_uuid(),
    class_code text,
    class_name text DEFAULT 'No name'::text,
    class_color text DEFAULT '#FFD700'::text
);


--
-- Name: TABLE teacher_class_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.teacher_class_code IS 'class code for teachers';


--
-- Name: teacher_class_code_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.teacher_class_code ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teacher_class_code_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_class_code class_code_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_class_code
    ADD CONSTRAINT class_code_pkey PRIMARY KEY (id);


--
-- Name: lecture_progress lecture_progress_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lecture_progress
    ADD CONSTRAINT lecture_progress_pkey PRIMARY KEY (uuid);


--
-- Name: physical_fitness_test physical_fitness_test_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.physical_fitness_test
    ADD CONSTRAINT physical_fitness_test_pkey PRIMARY KEY (id);


--
-- Name: physical_fitness_test physical_fitness_test_uuid_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.physical_fitness_test
    ADD CONSTRAINT physical_fitness_test_uuid_key UNIQUE (uuid);


--
-- Name: profile profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile
    ADD CONSTRAINT profile_pkey PRIMARY KEY (uuid);


--
-- Name: quiz_progress quiz_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_progress
    ADD CONSTRAINT quiz_pkey PRIMARY KEY (id);


--
-- Name: quiz quiz_pkey1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz
    ADD CONSTRAINT quiz_pkey1 PRIMARY KEY (id);


--
-- Name: teacher_class_code teacher_class_code_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teacher_class_code
    ADD CONSTRAINT teacher_class_code_pkey PRIMARY KEY (id);


--
-- Name: student_class_code class_code_uuid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_class_code
    ADD CONSTRAINT class_code_uuid_fkey FOREIGN KEY (uuid) REFERENCES public.profile(uuid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: lecture_progress lecture_progress_uuid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lecture_progress
    ADD CONSTRAINT lecture_progress_uuid_fkey FOREIGN KEY (uuid) REFERENCES public.profile(uuid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: physical_fitness_test physical_fitness_test_uuid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.physical_fitness_test
    ADD CONSTRAINT physical_fitness_test_uuid_fkey FOREIGN KEY (uuid) REFERENCES public.profile(uuid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: quiz_progress quiz_progress_quiz_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_progress
    ADD CONSTRAINT quiz_progress_quiz_id_fkey FOREIGN KEY (quiz_id) REFERENCES public.quiz(id);


--
-- Name: quiz_progress quiz_progress_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_progress
    ADD CONSTRAINT quiz_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profile(uuid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: teacher_class_code teacher_class_code_uuid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teacher_class_code
    ADD CONSTRAINT teacher_class_code_uuid_fkey FOREIGN KEY (uuid) REFERENCES public.profile(uuid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: lecture_progress Allow users to update their own data; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow users to update their own data" ON public.lecture_progress FOR INSERT TO authenticated WITH CHECK ((( SELECT auth.uid() AS uid) = uuid));


--
-- Name: student_class_code Enable delete for users based on user_id; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable delete for users based on user_id" ON public.student_class_code FOR DELETE USING ((( SELECT auth.uid() AS uid) = uuid));


--
-- Name: teacher_class_code Enable delete for users based on user_id; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable delete for users based on user_id" ON public.teacher_class_code FOR DELETE USING ((( SELECT auth.uid() AS uid) = uuid));


--
-- Name: physical_fitness_test Enable insert for authenticated users only; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable insert for authenticated users only" ON public.physical_fitness_test FOR INSERT TO authenticated WITH CHECK ((( SELECT auth.uid() AS uid) = uuid));


--
-- Name: profile Enable insert for authenticated users only; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable insert for authenticated users only" ON public.profile FOR INSERT TO authenticated WITH CHECK ((( SELECT auth.uid() AS uid) = uuid));


--
-- Name: quiz_progress Enable insert for authenticated users only; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable insert for authenticated users only" ON public.quiz_progress FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: student_class_code Enable insert for authenticated users only; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable insert for authenticated users only" ON public.student_class_code FOR INSERT TO authenticated WITH CHECK ((( SELECT auth.uid() AS uid) = uuid));


--
-- Name: teacher_class_code Enable insert for authenticated users only; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable insert for authenticated users only" ON public.teacher_class_code FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: lecture_progress Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON public.lecture_progress FOR SELECT USING (true);


--
-- Name: physical_fitness_test Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON public.physical_fitness_test FOR SELECT USING (true);


--
-- Name: profile Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON public.profile FOR SELECT USING (true);


--
-- Name: quiz Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON public.quiz FOR SELECT USING (true);


--
-- Name: quiz_progress Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON public.quiz_progress FOR SELECT USING (true);


--
-- Name: student_class_code Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON public.student_class_code FOR SELECT USING (true);


--
-- Name: teacher_class_code Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON public.teacher_class_code FOR SELECT USING (true);


--
-- Name: lecture_progress Enable update for users based on email; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable update for users based on email" ON public.lecture_progress FOR UPDATE USING ((( SELECT auth.uid() AS uid) = uuid)) WITH CHECK (true);


--
-- Name: profile Enable update for users based on email; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable update for users based on email" ON public.profile FOR UPDATE USING (((( SELECT auth.jwt() AS jwt) ->> 'email'::text) = email)) WITH CHECK (((( SELECT auth.jwt() AS jwt) ->> 'email'::text) = email));


--
-- Name: quiz_progress Enable update for users based on email; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable update for users based on email" ON public.quiz_progress FOR UPDATE USING ((( SELECT auth.uid() AS uid) = user_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: teacher_class_code Enable update for users based on email; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable update for users based on email" ON public.teacher_class_code FOR UPDATE USING ((( SELECT auth.uid() AS uid) = uuid)) WITH CHECK ((( SELECT auth.uid() AS uid) = uuid));


--
-- Name: physical_fitness_test Enable update for users based on uuid; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable update for users based on uuid" ON public.physical_fitness_test FOR UPDATE USING ((( SELECT auth.uid() AS uid) = uuid)) WITH CHECK (true);


--
-- Name: student_class_code Enable update for users based on uuid; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable update for users based on uuid" ON public.student_class_code FOR UPDATE USING ((( SELECT auth.uid() AS uid) = uuid)) WITH CHECK (true);


--
-- Name: quiz Policy with table joins; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Policy with table joins" ON public.quiz FOR UPDATE USING (true);


--
-- Name: quiz_progress Policy with table joins; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Policy with table joins" ON public.quiz_progress FOR UPDATE USING (true);


--
-- Name: lecture_progress; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.lecture_progress ENABLE ROW LEVEL SECURITY;

--
-- Name: physical_fitness_test; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.physical_fitness_test ENABLE ROW LEVEL SECURITY;

--
-- Name: profile; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.profile ENABLE ROW LEVEL SECURITY;

--
-- Name: quiz; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.quiz ENABLE ROW LEVEL SECURITY;

--
-- Name: quiz_progress; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.quiz_progress ENABLE ROW LEVEL SECURITY;

--
-- Name: student_class_code; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.student_class_code ENABLE ROW LEVEL SECURITY;

--
-- Name: teacher_class_code; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.teacher_class_code ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict VAcpTeu0Xfajg5491wqWCtglPiSqrqOLgdSdUIeBYZbFdm0kb4NspPeqTioea7B

